version: '3.7'
services:

  # JMeter Slave
  # ============================================================================
  jmeter-slave-0:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave-0
    environment:
      - SERVER_RMI_PORT=7000
      - CLIENT_RMI_PORT=60000
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    networks:
      - jmeter-network

  jmeter-slave-1:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave-1
    environment:
      - SERVER_RMI_PORT=7000
      - CLIENT_RMI_PORT=60000
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    networks:
      - jmeter-network

  jmeter-slave-2:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave-2
    environment:
      - SERVER_RMI_PORT=7000
      - CLIENT_RMI_PORT=60000
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    networks:
      - jmeter-network

  # JMeter master
  # ============================================================================
  jmeter-master:
    build: ./jmeter-master
    image: jmeter-cluster/jmeter-master
    container_name: jmeter-master
    environment:
      - CLIENT_RMI_PORT=60000
      - CLIENT_ENGINE_PORT=4445
      - REMOTE_HOSTS=jmeter-slave-0,jmeter-slave-1,jmeter-slave-2
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://jmeter-slave-0:60000 \
                  -wait=tcp://jmeter-slave-1:60000 \
                  -wait=tcp://jmeter-slave-2:60000 \
                  -timeout=300s -- &&
      /docker-entrypoint.sh"]
    volumes:
      - ./jmeter-master/logs:/logs
      - agent-vol:/agent
    networks:
    - jmeter-network

volumes:
  agent-vol:

networks:
  jmeter-network:
    driver: bridge
