version: '3.7'
services:

  # InspectIT
  # ============================================================================
  # Agent
  agent:
    build: ./agent
    image: jmeter-cluster/inspectit-agent
    container_name: jmeter-cluster-agent
    volumes:
      - agent-vol:/agent

  # Config server
  ocelot-config-server:
    image: inspectit/inspectit-ocelot-configurationserver:${INSPECTIT_OCELOT_VERSION}
    container_name: ocelot-config-server
    environment:
      - INSPECTIT_CONFIG_SERVER_WORKING_DIRECTORY=/configuration-server
      - INSPECTIT_CONFIG_SERVER_DEFAULT_USER_PASSWORD=demo
    volumes:
      - ./configuration-server:/configuration-server
    networks:
      - jmeter-network
    ports:
      - 8090:8090

  # Metrics
  # ============================================================================
  # InfluxDB
  influxdb-server:
    image: influxdb:1.7.1
    container_name: inspectit-influxdb-server
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./influxdb-server:/docker-entrypoint-initdb.d
    networks:
      - jmeter-network
    ports:
      - 8086:8086

  # Prometheus
  prometheus-server:
    image: prom/prometheus:v2.9.2
    container_name: prometheus
    depends_on:
      - jmeter-master
    volumes:
      - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jmeter-network
    ports:
      - 9090:9090

  # Grafana
  grafana-server:
    build: ./grafana-server
    image: jmeter-cluster/jmeter-grafana-server
    container_name: inspectit-grafana-server
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel
    volumes:
      - ./grafana-server/provisioning:/usr/share/grafana/custom/
    depends_on:
      - prometheus-server
    networks:
      - jmeter-network
    ports:
      - 3000:3000

  # Trazing
  # ============================================================================
  # Zipkin
  zipkin-server:
    image: openzipkin/zipkin
    container_name: inspectit-zipkin-server
    networks:
      - jmeter-network
    ports:
      - 9411:9411

  # JMeter Slave
  # ============================================================================
  jmeter-slave-0:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave-0
    environment:
      # JMeter server configuration
      - JMETER_SERVER_RMI_PORT=7000
      - JMETER_CLIENT_RMI_PORT=60000
      # Inspect IT agent configuration
      - INSPECTIT_SERVICE_NAME=jmeter-slave-0
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://ocelot-config-server:8090 \
                  -wait=tcp://influxdb-server:8086 \
                  -wait=tcp://zipkin-server:9411 \
                  -timeout=300s -- &&
      /docker-entrypoint.sh"]
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    networks:
      - jmeter-network
    ports:
      - 9270:9270

  jmeter-slave-1:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave-1
    environment:
      # JMeter server configuration
      - JMETER_SERVER_RMI_PORT=7000
      - JMETER_CLIENT_RMI_PORT=60000
      # Inspect IT agent configuration
      - INSPECTIT_SERVICE_NAME=jmeter-slave-1
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://ocelot-config-server:8090 \
                  -wait=tcp://influxdb-server:8086 \
                  -wait=tcp://zipkin-server:9411 \
                  -timeout=300s -- &&
      /docker-entrypoint.sh"]
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    networks:
      - jmeter-network
    ports:
      - 9271:9270

  jmeter-slave-2:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave-2
    environment:
      # JMeter server configuration
      - JMETER_SERVER_RMI_PORT=7000
      - JMETER_CLIENT_RMI_PORT=60000
      # Inspect IT agent configuration
      - INSPECTIT_SERVICE_NAME=jmeter-slave-2
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://ocelot-config-server:8090 \
                  -wait=tcp://influxdb-server:8086 \
                  -wait=tcp://zipkin-server:9411 \
                  -timeout=300s -- &&
      /docker-entrypoint.sh"]
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    networks:
      - jmeter-network
    ports:
      - 9272:9270

  # JMeter master
  # ============================================================================
  jmeter-master:
    build: ./jmeter-master
    image: jmeter-cluster/jmeter-master
    container_name: jmeter-master
    environment:
      # JMeter server configuration
      - JMETER_CLIENT_RMI_PORT=60000
      - JMETER_CLIENT_ENGINE_PORT=4445
      - JMETER_REMOTE_HOSTS=jmeter-slave-0,jmeter-slave-1,jmeter-slave-2
      # Experiment configuration
      - EXP_RUN_ID=dummy-id
      - EXP_RUN_NAME=dummy-name
      - EXP_START_TIME=2000-01-01T12:00:11Z
      - EXP_TEST_PLAN_URL=https://github.com/adriannovegil/jmeter-dummy-test-plan
      - EXP_TEST_PLAN_DIR=prometheus
      - EXP_TEST_PLAN_FILE_NAME=simple_prometheus_example.jmx
      # Inspect IT agent configuration
      - INSPECTIT_SERVICE_NAME=jmeter-master
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb-server:8086
      - INSPECTIT_EXPORTERS_TRACING_ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://jmeter-slave-0:60000 \
                  -wait=tcp://jmeter-slave-1:60000 \
                  -wait=tcp://jmeter-slave-2:60000 \
                  -timeout=300s -- &&
      /docker-entrypoint.sh"]
    volumes:
      - ./jmeter-master/logs:/logs
      - agent-vol:/agent
    networks:
    - jmeter-network
    ports:
      - 9273:9270

volumes:
  agent-vol:

networks:
  jmeter-network:
    driver: bridge
