version: '3.7'
services:

  # JMeter Slave
  jmeter-slave:
    build: ./jmeter-slave
    image: jmeter-cluster/jmeter-slave
    container_name: jmeter-slave
    environment:
      #- SERVER_HOST_NAME=jmeter-slave
      - SERVER_RMI_PORT=7000
      - CLIENT_RMI_PORT=60000
    volumes:
      - ./jmeter-slave/logs:/logs
      - agent-vol:/agent
    deploy:
      replicas: 2
    networks:
      - jmeter-network

  # JMeter master
  jmeter-master:
    build: ./jmeter-master
    image: jmeter-cluster/jmeter-master
    container_name: jmeter-master
    environment:
      #- SERVER_HOST_NAME=jmeter-slave
      #- SERVER_RMI_PORT=7000
      - CLIENT_RMI_PORT=60000
      - CLIENT_ENGINE_PORT=4445
      - REMOTE_HOSTS=jmeter-slave
    volumes:
      - ./jmeter-master/logs:/logs
      - agent-vol:/agent
    networks:
    - jmeter-network
    #ports:
    #  - 8398:1099
    #  - 8399:4445

volumes:
  agent-vol:

networks:
  jmeter-network:
    driver: bridge
